services:
  web:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.back
    container_name: fastapi_laah
    env_file: .env
    volumes:
      - ./apps/api:/app
    ports:
      - "8888:8000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db_laah
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - app_network

  front:
    build:
      context: ./apps/front
      dockerfile: Dockerfile.front
    container_name: app_front_laah
    volumes:
      - ./apps/front:/app
      - /app/node_modules # évite d'écraser les modules
    ports:
      - "5175:5173"  # accès sur localhost:5175
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_laah
    restart: always
    ports:
      - "8085:8080"
    networks:
      - app_network

volumes:
  postgres_data:

# Réseaux pour la communication entre services
networks:
  app_network:
    driver: bridge