/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsIndexRouteImport } from './routes/formations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FormationsIdIndexRouteImport } from './routes/formations/$id/index'
import { Route as FormationsIdSessionsRouteImport } from './routes/formations/$id/sessions'
import { Route as AdminDashboardFormationsIndexRouteImport } from './routes/admin/dashboard/formations/index'
import { Route as AdminDashboardFormationsNewRouteImport } from './routes/admin/dashboard/formations/new'
import { Route as AdminDashboardFormationsIdEditRouteImport } from './routes/admin/dashboard/formations/$id/edit'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIdIndexRoute = FormationsIdIndexRouteImport.update({
  id: '/formations/$id/',
  path: '/formations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIdSessionsRoute = FormationsIdSessionsRouteImport.update({
  id: '/formations/$id/sessions',
  path: '/formations/$id/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardFormationsIndexRoute =
  AdminDashboardFormationsIndexRouteImport.update({
    id: '/admin/dashboard/formations/',
    path: '/admin/dashboard/formations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardFormationsNewRoute =
  AdminDashboardFormationsNewRouteImport.update({
    id: '/admin/dashboard/formations/new',
    path: '/admin/dashboard/formations/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardFormationsIdEditRoute =
  AdminDashboardFormationsIdEditRouteImport.update({
    id: '/admin/dashboard/formations/$id/edit',
    path: '/admin/dashboard/formations/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/formations': typeof FormationsIndexRoute
  '/formations/$id/sessions': typeof FormationsIdSessionsRoute
  '/formations/$id': typeof FormationsIdIndexRoute
  '/admin/dashboard/formations/new': typeof AdminDashboardFormationsNewRoute
  '/admin/dashboard/formations': typeof AdminDashboardFormationsIndexRoute
  '/admin/dashboard/formations/$id/edit': typeof AdminDashboardFormationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin': typeof AdminIndexRoute
  '/formations': typeof FormationsIndexRoute
  '/formations/$id/sessions': typeof FormationsIdSessionsRoute
  '/formations/$id': typeof FormationsIdIndexRoute
  '/admin/dashboard/formations/new': typeof AdminDashboardFormationsNewRoute
  '/admin/dashboard/formations': typeof AdminDashboardFormationsIndexRoute
  '/admin/dashboard/formations/$id/edit': typeof AdminDashboardFormationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/formations/': typeof FormationsIndexRoute
  '/formations/$id/sessions': typeof FormationsIdSessionsRoute
  '/formations/$id/': typeof FormationsIdIndexRoute
  '/admin/dashboard/formations/new': typeof AdminDashboardFormationsNewRoute
  '/admin/dashboard/formations/': typeof AdminDashboardFormationsIndexRoute
  '/admin/dashboard/formations/$id/edit': typeof AdminDashboardFormationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/testimonials'
    | '/admin'
    | '/formations'
    | '/formations/$id/sessions'
    | '/formations/$id'
    | '/admin/dashboard/formations/new'
    | '/admin/dashboard/formations'
    | '/admin/dashboard/formations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/testimonials'
    | '/admin'
    | '/formations'
    | '/formations/$id/sessions'
    | '/formations/$id'
    | '/admin/dashboard/formations/new'
    | '/admin/dashboard/formations'
    | '/admin/dashboard/formations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/testimonials'
    | '/admin/'
    | '/formations/'
    | '/formations/$id/sessions'
    | '/formations/$id/'
    | '/admin/dashboard/formations/new'
    | '/admin/dashboard/formations/'
    | '/admin/dashboard/formations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
  FormationsIdSessionsRoute: typeof FormationsIdSessionsRoute
  FormationsIdIndexRoute: typeof FormationsIdIndexRoute
  AdminDashboardFormationsNewRoute: typeof AdminDashboardFormationsNewRoute
  AdminDashboardFormationsIndexRoute: typeof AdminDashboardFormationsIndexRoute
  AdminDashboardFormationsIdEditRoute: typeof AdminDashboardFormationsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/$id/': {
      id: '/formations/$id/'
      path: '/formations/$id'
      fullPath: '/formations/$id'
      preLoaderRoute: typeof FormationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/$id/sessions': {
      id: '/formations/$id/sessions'
      path: '/formations/$id/sessions'
      fullPath: '/formations/$id/sessions'
      preLoaderRoute: typeof FormationsIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/formations/': {
      id: '/admin/dashboard/formations/'
      path: '/admin/dashboard/formations'
      fullPath: '/admin/dashboard/formations'
      preLoaderRoute: typeof AdminDashboardFormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/formations/new': {
      id: '/admin/dashboard/formations/new'
      path: '/admin/dashboard/formations/new'
      fullPath: '/admin/dashboard/formations/new'
      preLoaderRoute: typeof AdminDashboardFormationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/formations/$id/edit': {
      id: '/admin/dashboard/formations/$id/edit'
      path: '/admin/dashboard/formations/$id/edit'
      fullPath: '/admin/dashboard/formations/$id/edit'
      preLoaderRoute: typeof AdminDashboardFormationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  TestimonialsRoute: TestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  FormationsIndexRoute: FormationsIndexRoute,
  FormationsIdSessionsRoute: FormationsIdSessionsRoute,
  FormationsIdIndexRoute: FormationsIdIndexRoute,
  AdminDashboardFormationsNewRoute: AdminDashboardFormationsNewRoute,
  AdminDashboardFormationsIndexRoute: AdminDashboardFormationsIndexRoute,
  AdminDashboardFormationsIdEditRoute: AdminDashboardFormationsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
